### ISSUE TITLE
Сообщения вне коллбеков

### ISSUE THREAD

**Issue by Tpona** [bifot/node-vk-bot-api#2]
Привет, хочу делать рассылку по времени.
В апи есть соллбеки и ответ шлется только на приходящее сообщение.
Вне коллбеков отправить сообщение через bot.execute? 
Можно пример вызова описать для этого метода?

**Comment by binjospookie** [comment]
@Tpona я реализовывал схожий функционал у себя. Создал отдельный модуль `Seller` и перебирал в нём массив `chatId`, который собирал при обращении пользователя к боту.

**Comment by bifot** [comment]
Я правильно понял, что ты просто хочешь отправить сообщение? (не коллбэк на какое-то действие)

**Comment by Tpona** [comment]
@bifot  Верно )

**Comment by Tpona** [comment]
@binjospookie да с этим вопросов нет, просто в данном модуле не нашел метода отправить сообщение без использования контекста, который приходит в коллбек, думаю не лишним будет.
Как я понял, есть execute для этого?

**Comment by binjospookie** [comment]
@Tpona так надо же знать получателя хотя бы...

**Comment by Tpona** [comment]
@binjospookie так я знаю, при первом сообщении боту я сохраняю его id в базу

**Comment by bifot** [comment]
Можешь использовать метод bot.reply (документация по нему — https://github.com/bifot/node-vk-bot-api/blob/master/README.md#sendmessagepeerid-command-callback).
